# Generated by Django 5.1.1 on 2024-09-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='newspaper',
            field=models.CharField(max_length=255),
        ),
    ]
